### ISSUE TITLE
Min Android SDK version suggestions

### ISSUE THREAD

**Issue by Romeo0906** [regulaforensics/cordova-plugin-documentreader#2]
Hello dear, I am a developer of IATA and we are heading to using your plugin, we find that in your config file, the supported minimum Android SDK version supported is 19, I think it may be some kind of strict.

If you really require that, please ignore my suggestion, if not, it will be better if you make it more compatible.

**Comment by DmitrySmolyakov** [comment]
Romeo, currently we are really require SDK version 19. But we try to decrease version in future. Thank you for your request.
