### ISSUE TITLE
Problem with importing RGLDocumentReader.h

### ISSUE THREAD

**Issue by michelj90** [regulaforensics/cordova-plugin-documentreader#4]
Hello,

Currently when i want to build my project in Xcode i get an error in the RGLDocumentReader.m file:
<img width="1374" alt="schermafbeelding 2018-01-15 om 12 23 25" src="https://user-images.githubusercontent.com/1065340/34940215-fe0e2254-f9ee-11e7-9cb1-951fb419957f.png">

It seems like it's nog capable of finding the "RGLDocumentReader.h", although it's been included in the header of the file. 

I used a new Cordova project and followed the the steps described in the readme.MD file to build the demo application. I have absolutely no idea what's going wrong, can you help me fix this issue? 

Regards,
Michel

**Versions:**
POD: 1.3.1
Xcode: 9.2
Cordova: 8.0.0
Cordova-plugin-documentreader: 0.4.1.

**Comment by DmitrySmolyakov** [comment]
Hello, Michaelle. Sorry, but currently framework is not working. We will prepare update shourtly. Thank you for your feedback.

**Comment by michelj90** [comment]
@DmitrySmolyakov Thnx for your response, how long do you think it will take to fix this issue? 
Also older versions of this plugin, did they work in the past?

**Comment by McNull** [comment]
Hi,

a workaround is specifying an older dependency of the `DocumentReader` pod in the `plugins/cordova-plugin-documentreader/plugin.xml`:

```
<plugin>
    <!-- ... -->
    <pod name="DocumentReader" version="2.4.0"/>
    <pod name="DocumentReaderMRZBarcode" version="1.0.0"/>
    <!-- ... -->
</plugin>
```

**Comment by DmitrySmolyakov** [comment]
Pods version was updated
