### ISSUE TITLE
Compatibility with MobileIron AppConnect

### ISSUE THREAD

**Issue by IAmCoder** [regulaforensics/cordova-plugin-documentreader#5]
I have a project with the MobileIron AppConnect plugin for cordova (<plugin name="com.mobileiron.cordova.appconnect" spec="^3.5.0.56" />). It works great with version 0.2.1 of cordova-plugin-documentreader, but with any version after that, the MobileIron@Work app no longer launches when the app starts up. Do you happen to have any ideas off the top of your head of what could be causing it?

**Comment by DmitrySmolyakov** [comment]
@IAmCoder Try to use latest @4.0.3 version, should resolve that issue

**Comment by IAmCoder** [comment]
Elite, thanks!
